### ISSUE TITLE
transform.localPosition assign attempt for 'ListBox_0' is not valid : Unity 5

### ISSUE THREAD

**Issue by AdamAngle** [LanKuDot/game_modules#1]
Hello, I am currently attempting to use this module for Unity3D in my game, however, I have come across an issue. Whenever I try to launch the application, it makes most of the boxes move toward the center, and displays this error message repeatedly in the console:

> transform.localPosition assign attempt for 'ListBox_1' is not valid. Input localPosition is { NaN, 0.000000, 0.000000 }.
> UnityEngine.Transform:set_localPosition(Vector3)
> ListBox:updateXPosition() (at Assets/ListBox.cs:147)
> ListBox:checkBoundaryY() (at Assets/ListBox.cs:185)
> ListBox:updatePosition(Vector3) (at Assets/ListBox.cs:135)
> ListBox:Update() (at Assets/ListBox.cs:101)

The items in the scene look like this (There are supposed to be 5 items):

![errorimg](https://cloud.githubusercontent.com/assets/12690737/16573960/8fa964aa-422e-11e6-9045-315d846c2957.png)

Image of the ListBank GameObject:

![errorimg2](https://cloud.githubusercontent.com/assets/12690737/16574008/351193b8-422f-11e6-9e8f-e5d47725cc81.png)

**Comment by LanKuDot** [comment]
ListBox will initialize its variables from ListPositionCtrl in Start(). Make sure the execution order of the ListPositionCtrl is prior to ListBox.

**Comment by AdamAngle** [comment]
Ah, yes. Thank you for this fix! I would have never thought of changing the execution order.

**Comment by duonglkh** [comment]
I can not resolve this problem, please please help
![ssss](https://user-images.githubusercontent.com/25151185/34767161-00f9629e-f62a-11e7-94d8-f10fe1346f9c.png)

**Comment by LanKuDot** [comment]
Hi, could you paste the detail of the error message and the call stack?
