### ISSUE TITLE
Scroll inertia

### ISSUE THREAD

**Issue by jjrage** [LanKuDot/game_modules#11]
Hello. Is it possible to implement some scroll inertia like on this video?
https://youtu.be/q9jMS-bQmTU

**Comment by LanKuDot** [comment]
How about increase the value of "Box sliding frames" and decrease the "Box sliding speed factor"?
But in the current version, the inertial scrolling effect is only applied at the end of the scrolling.

**Comment by jjrage** [comment]
It works much better, thank you. But I meant adding some velocity value to scrolling distance. The problem is that the scrolling effect is affected not only by the distance but also by the number of frames for this

**Comment by LanKuDot** [comment]
Such as a single value "deceleration"? And the list will stop when the velocity is small enough.

**Comment by jjrage** [comment]
Yes. Because if I increase the value of "Box sliding frames" it value is same for scrolling regardless of the distance I need to scroll (for example it good for long scroll but bad for short, when I need to scroll only one element). I have achieved close result by setting input delta distance (which is taken from mouse), asign it to _slidingDistance and decrease it every frame. Also I changed condition "if (_slidingFramesLeft > 0)" in Update to "if (_deltaInputPos_L> 0)". But now it can't properly set to center when sliding is over. So what is best way to improve this? Should I refuse frames values from scrolling and change positions of listbox only by _deltaInputPos_L or it's better to add some velocity value? (I tried this but I don't understand where I should put it value)

**Comment by LanKuDot** [comment]
The sliding distance is decided by the dragging distance ([ListPositionCtrl.cs_Line 305](https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/ListPositionCtrl.cs#L305)), and `SetSlidingEffect()` is called at the end of dragging. So I think you can set its value by calculating the closest distance to the center, like what `FindDeltaPositionToCenter()` do (However, this function doesn't take the sliding direction into account).

The list will move that distance in "Box sliding frames" and the moving distance for each frame is decided by `lerp(0, slidingDistanceLeft, "Box sliding speed factor")`.

By the way, there is an option "Align to center" which makes the list align to the center after sliding, but the movement is not really good.

**Comment by LanKuDot** [comment]
Hi! How's it going? I get an idea that makes the sliding effect better. Maybe I can implement it latter.

**Comment by jjrage** [comment]
Hi.
Now I'm ittle bisy to implement your recomendations so I put it off for later. That's good, I will wait for it!
Also do we talk about same "better" implementation? Because I'm oriented on sliding effect like in Android and IOS Date pickers:
https://www.youtube.com/watch?v=hwe1abDO2Ag
https://www.youtube.com/watch?v=aa-lNWUVY7g

**Comment by LanKuDot** [comment]
Yes, just like the effect in the videos. Some users said that the "two-step" effect looked weird before, but I couldn't make it better.
My idea is that finding the distance to the center when the mouse releases, instead of when the list stops. So the list will slide for a proper distance and then stop, not to move again to make it align at the center (which is two-step).

**Comment by LanKuDot** [comment]
Hi, @jjrage . It has been a long time. I am developing the new version now. The movement of the list is controlled by the `AnimationCurve`. Here is the screenshot. I think it is quite better now :D
![](https://i.imgur.com/Zs9zS4t.gif)

**Comment by LanKuDot** [comment]
The better movement is implemented in the new version. 😃
