### ISSUE TITLE
list of over 100 objects

### ISSUE THREAD

**Issue by Hoomann** [LanKuDot/game_modules#12]
hi there...first thanks for the fantastic work
i realized that when you have a long list of objects to show the center box object size is not much bigger than the previous and the next object compared to a shorter list with the same parameters.
is there any work around to it?
in my case i have a list of 118 items to show in gallery and i want the center object to be bigger than the ones beside it

**Comment by LanKuDot** [comment]
The scaling of boxes is distributed between 1 to 1 + scaleFactor. For example:
![Imgur](https://i.imgur.com/mxnT3LW.png)
Therefore, the number of boxes will affect the scaling of the boxes between the end and the center.
If you don't need to display 118 items at a time, reduce the number of boxes to make it looks properly. But if you need, you can modify the function `UpdateSize()` in `ListBox.cs`. The original algorithm is to `lerp` the scale according to the relative position between the list end and the center.

**Comment by Hoomann** [comment]
i think i'll try modifying it see if i can get the proper result.
and one other thing..the start of the list doesn't align to middle until i try to drag it a little bit
this is an image at first -----> https://ibb.co/D8pM8cw
this is the one that should be -----> https://ibb.co/mzY1NWW

**Comment by LanKuDot** [comment]
Oh, let's right. If there are even number of boxes used, it will be like that.
Remove the `if` statement and the code in it in function `InitialPosition()` in `ListBox.cs`, just leave the remaining code in `else` statement.

**Comment by Hoomann** [comment]
perfect..thanks

**Comment by Hoomann** [comment]
for the first question, do you think if i say the last box in our list is the next 10th box not the 118th and do it every time the centered box is changed, i will get the result that i desire?

**Comment by LanKuDot** [comment]
I think it will. The purpose of this module is using less boxes to show more contents. According to the screenshot you gave, I think 5 boxes is enough. You could provide a `ListBank` ([link](https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/README.md#create-listbank)) which storing all contents and modify the `UpdateDisplayContent()` in `ListBox.cs` for updating the content in the way you want.
Therefore, no matter the number of contents, there are the same number of boxes, and the size of the list is the same.
