### ISSUE TITLE
Linear list doesn't scroll to the right

### ISSUE THREAD

**Issue by khmaies5** [LanKuDot/game_modules#15]
i set up the list as indicated in the instruction, but in the linear i can't scroll back with the first two button but if i scroll to the middle of the list i can scroll back one or two buttons.
also i set the align middle to true but only the first two are aligned well and the rest are not

**Comment by LanKuDot** [comment]
Hi, could you give me the setting of the list and the screenshot of the list in the scene?

**Comment by khmaies5** [comment]
![image](https://user-images.githubusercontent.com/15824344/93459332-77386e00-f8d9-11ea-9af2-54426d235508.png)
![image](https://user-images.githubusercontent.com/15824344/93459357-80c1d600-f8d9-11ea-8190-949767b2604d.png)
![image](https://user-images.githubusercontent.com/15824344/93459400-8d462e80-f8d9-11ea-8e58-b08ed925c2c0.png)

**Comment by LanKuDot** [comment]
It seems that the movement curve for the mode drag is incorrect. It should be from a positive value to 0.
Was your control mode the mouse wheel at the first? I checked that if the movement curve for the mode mouse wheel is from high to low, the list couldn't be moved. It should be from 0 to 1 in this mode.

For the second question, it's because that the box position is equally divided. Therefore, if the scale value of the box differs a lot, it will look like the gap between boxes is large.

**Comment by khmaies5** [comment]
![image](https://user-images.githubusercontent.com/15824344/93480153-0acb6800-f8f5-11ea-92e9-a066017381a8.png)
here is the movement curve i didn't change it its the default
if i create new list with the same curves it works the first time

**Comment by LanKuDot** [comment]
Here is what I tested and the setting is similar to yours:
![Imgur](https://i.imgur.com/Ejqu9YV.gif)
It works fine. But how do I reproduce the problem you mentioned?

**Comment by khmaies5** [comment]
thats the problem i dont know what went wrong, i just discovered that its not returning the correct centred button index

**Comment by LanKuDot** [comment]
No, It will return the content ID not the box ID.

**Comment by khmaies5** [comment]
sorry i meant its not returning the centered content ID

**Comment by LanKuDot** [comment]
Which function do you use? `ListPositionCtrl.GetCenteredContentID()`?
This method is just finding the box whose local position is nearest to 0 and returning the ID it holds.

**Comment by khmaies5** [comment]
''' public void GetSelectedContentID(int contentID)
    {
        Debug.Log("centred ###### " + list.GetCenteredContentID());
        if (list.GetCenteredContentID() == contentID)
        {
            Debug.Log("Selected content ID: " + contentID.ToString() +
            ", Content: " + GetListContent(contentID));

        }

**Comment by LanKuDot** [comment]
It works normally:
![Imgur](https://i.imgur.com/2fqYsI0.gif)
By the way, if you doesn't click on buttons, you can't drag the list.

**Comment by LanKuDot** [comment]
It's odd. Which version of Unity are you using?

**Comment by khmaies5** [comment]
i am using 2019.4.2 
i deleted the lists and recreated them from scratch and now they are working fine

**Comment by LanKuDot** [comment]
Thankfully! 😄 
The issue is closed.
It's welcome to reopen the issue If you have any problem with using it.
