### ISSUE TITLE
Even number of Objects in Content

### ISSUE THREAD

**Issue by Timisko** [LanKuDot/game_modules#18]
Hello 💯. I have some problem in my unity game. 🥇 When I have even number of objects circular menu always starts between two of them.

**Comment by LanKuDot** [comment]
Hi! You could remove [line 171 to 174 in `ListPositionCtrl.cs`](https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/ListPositionCtrl.cs#L171) and [line 106 to 108 in `ListBox.cs`](https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/ListBox.cs#L106).

**Comment by Timisko** [comment]
Hi! You could remove line 171 to 174 in ListPositionCtrl.cs and line 106 to 108 in ListBox.cs. 
THANKS Kun-Yi Li
