### ISSUE TITLE
Display Centered Content ID doesnt work

### ISSUE THREAD

**Issue by Timisko** [LanKuDot/game_modules#19]
Hi I tried your script from PDF to get centered contet id but it doesnt work. 
![Screenshot_1](https://user-images.githubusercontent.com/80092061/113632159-ece40b80-966a-11eb-945c-71e4e632596a.png)
![Screenshot_3](https://user-images.githubusercontent.com/80092061/113632172-ef466580-966a-11eb-9966-74303933b29f.png)

**Comment by LanKuDot** [comment]
Could you provide the detailed call stack? And Were the `list` and `listBank` both assigned in the inspector?

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113716113-89012780-96ea-11eb-8b75-746f3ba94ae9.png)
![image](https://user-images.githubusercontent.com/80092061/113716267-b3eb7b80-96ea-11eb-8968-89d7ef1f5c45.png)

Callback function worked for me but there is error in "int contentID = list.GetCenteredContentID();"

![image](https://user-images.githubusercontent.com/80092061/113716515-fb720780-96ea-11eb-94b5-c4c7284198c2.png)

**Comment by LanKuDot** [comment]
Did you assign the `list` to the `MainMenuScript` in the inspector? Put a code `Debug.Log(list)` before the line 16, and check if it throws the exception.

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113729013-e69b7100-96f6-11eb-8fd3-70563121c54b.png)
Its throwing error

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113730180-f4052b00-96f7-11eb-921f-cda7e74a24c1.png)
Sorry I uploaded wrong picture

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113730401-26168d00-96f8-11eb-940c-703bba8f00c9.png)
:D again wrong picture

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113730501-3e86a780-96f8-11eb-82de-c82271c141ff.png)

**Comment by LanKuDot** [comment]
Check the your `MainMenuScript` in the inspector. Make sure that the `ListPositionCtrl` is assigned to the `list` field of `MainMenuScript`.

**Comment by Timisko** [comment]
![image](https://user-images.githubusercontent.com/80092061/113775649-56c2ea80-9729-11eb-9ef6-5b861331b656.png)

**Comment by LanKuDot** [comment]
Which gameobject uses this script? Check that.

**Comment by Timisko** [comment]
Button that show you centered id uses the mainmenuscript

**Comment by Timisko** [comment]
Okay I found error.. I didnt attached to button main menu script list .. Thanks :D 
But now it only back me first ID

**Comment by LanKuDot** [comment]
Was the returned ID the same as the centered content shown in the list?

**Comment by Timisko** [comment]
It was problem with content.. I dont know what was the problem but I restored older version and now is everything working.. Thanks for your time and help :)))
