### ISSUE TITLE
Infinite loop problem

### ISSUE THREAD

**Issue by ttnppedr** [LanKuDot/game_modules#23]
In ListBank if size of contents is zero it will encounter a infinite loop problem while executing.

**Comment by LanKuDot** [comment]
It is caused by rounding the initial content ID in the `ListBox.cs`. https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/ListBox.cs#L245
It will be fixed in the next version, and report an exception instead.

**Comment by LanKuDot** [comment]
Fixed in version 5. It is allowed to have no content in the list bank.
