### ISSUE TITLE
Function Linear Unexpected Behavior in Example Scene 

### ISSUE THREAD

**Issue by hacecc** [LanKuDot/game_modules#27]
Going to the scene **ControlMode** and using the **Function Linear** example has unwanted behavior. If you keep pressing on the top button the list will eventually disappear. If you also press the top button once then try to press the bottom button the list will not move. This is in Unity URP 2019.4.32f1 and i also tried it on 2021.1.28f1

**Comment by LanKuDot** [comment]
Which version are you using? I tested and it works fine.
Here is the correct behavior:
![gif](https://user-images.githubusercontent.com/2039072/141133472-e543524c-8bb0-473e-be93-cc486eb4df54.gif)

**Comment by hacecc** [comment]
Hmm well i tried both the github master branch and the asset store v5.0

First video is from github master branch and second is from the asset store. I started with a new URP sample project on 2019.4.32.

https://user-images.githubusercontent.com/71294327/141145624-0e678995-c596-4db9-ba05-6bfb996df04f.mp4


https://user-images.githubusercontent.com/71294327/141145646-0cd272a6-e141-4769-ae84-8b804409fc6b.mp4

.

**Comment by LanKuDot** [comment]
Ok. I tested the package and found the same problem.
Maybe I forgot to push some fixing commits. I will create a patch to the repo and the store.
The quick fix is that add `_toRunLateUpdate = true` to `ListPositionCtrl.SetUnitMove()`.
Thanks a lot.

**Comment by hacecc** [comment]
Awesome, thanks for the update!

**Comment by LanKuDot** [comment]
Fixed in the [Version 5.1](https://github.com/LanKuDot/game_modules/tree/CircularList_v5.1)
