### ISSUE TITLE
Unnable to start with empty list

### ISSUE THREAD

**Issue by Ensaurus** [LanKuDot/game_modules#41]
If starting with an empty list, _centeredBox is never initialized so when first element is added to the list, Refresh() on CircularScrollingList throws an error. 

Suggested fix: 
Rather than initializing candidateBox as null at the top of FindDeltaDistanceToCenter in ListPositionCtrl.cs, just initialize it as _listBoxes[0].

**Comment by LanKuDot** [comment]
This issue has been fixes in the version 6. Please check the new version.
