### ISSUE TITLE
supprot custom property curves?

### ISSUE THREAD

**Issue by feipinxiang** [LanKuDot/game_modules#45]
Is it possible to set some custom property curves? Such as "box canvaasGroup alpha curve" "box rotation curve"

**Comment by LanKuDot** [comment]
Hi, the quick solution is that override the [`OnBoxMoved()` of the `ListBox`](https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/Scripts/ListBox.cs#L77). The position ratio will be passed to the function which is from -1 to 1.
Then add the related curves to the `CircularScrollingList`, and access these curves by the property `ScrollingList` of the `ListBox`.

**Comment by feipinxiang** [comment]
Thanks for the answer. 
This method does not exist in the 6.1 version I am using, You haven't published it to Release yet. 
I will clone a copy and try it.
