### ISSUE TITLE
IntListBoxes inactive

### ISSUE THREAD

**Issue by Kumah1** [LanKuDot/game_modules#46]
IntListBoxes are set inactive when **initialize on Start** is marked in the "_CircularScrollingList_".
But when it's not marked it will remain visible in the scene but uncontrollable.
Please help.

**Comment by LanKuDot** [comment]
The list is usable only after it is initialized. If you want to control when to initialize the list, you could invoke the `CircularScrollingList.Initialize()` manually with the option `Initialize on Start` unchecked.

**Comment by LanKuDot** [comment]
If the problem doesn't fixed. Feel free to reopen the issue.
