### ISSUE TITLE
Circular or linear mode

### ISSUE THREAD

**Issue by LanKuDot** [LanKuDot/game_modules#7]
Linear mode is that the list is not a loop list. If it reaches the head or the end of the list, the circularList won't be dragged any further.

**Comment by nsebhastian** [comment]
Hi @LanKuDot can you provide any hint as to how to stop the circular scrolling? I'd like to implement this one to my unity game.


Thanks!

**Comment by LanKuDot** [comment]
Hi! The boxes checks the boundary in the function `ListBox.updatePosition` by invoking `ListBox.checkBoundaryY` or `ListBox.checkBoundaryX`. If these checkBoundary functions are commented, you can find that the list will keep going up or down. Therefore, you have to make the `ListPositionCtrl` know that the list reaches the end, so it won't keep update the position of boxes. (Maybe the signal can be sent from the boxes at two ends, when they reach at the certain position.)

**Comment by LanKuDot** [comment]
Implemented in CircularList_v3.
