### ISSUE TITLE
Move by Scroll wheel

### ISSUE THREAD

**Issue by aledg** [LanKuDot/game_modules#8]
Thank LanKuDot it's very nice your scripts Do you think that is possible use it also with the Scroll wheel of mouse ? where I have to change the script to enabled this feautures

**Comment by LanKuDot** [comment]
Hi. I made a very first version, but it looks glitchy. I think the problem is that the `mouseScrollDelta` is not non-zero in every frame when scrolling mouse wheel.
Here is the patch: https://gist.github.com/LanKuDot/d264e54cb8209971f38037c649d6f9b2

**Comment by aledg** [comment]
I try this code and work for me ...
I've change only the ListPOsitionCtrl.cs

`    void Update()
    {
        _storeInputPosition();
        scrollMouse();
    }

    void scrollMouse()
    {
        Debug.ClearDeveloperConsole();
        var d = Input.GetAxis("Mouse ScrollWheel");
        if (d > 0f)
        {
            nextContent();
        }
        else if (d < 0f)
        {
            lastContent();
        }

    }`

**Comment by LanKuDot** [comment]
The code is updated. And thank you again!
